### ISSUE TITLE
subscriptions recording duplicates

### ISSUE THREAD

**Issue by ryanchild** [dscottbuch/cTiVo#215] opened 2016-11-26 03:55 UTC
I noticed this awhile back, was hoping on debugging further but never found the time.  Now looking at Finder I notice there are several duplicate recordings for a subscription I started some time ago.  Last time I checked, several recordings were not getting added to the plist which I believe is where you said previously recorded subscription episodes were supposed to be tracked.  Sorry for not flagging earlier, you might choose to defer to 2.6 along with issue #196 

[com.cTiVo.cTiVo.plist.txt](https://github.com/dscottbuch/cTiVo/files/614041/com.cTiVo.cTiVo.plist.txt)
<img width="689" alt="screen shot 2016-11-25 at 8 47 27 pm" src="https://cloud.githubusercontent.com/assets/1109218/20637826/6486c400-b350-11e6-9724-d721abd4b579.png">

**Comment by mackworth** [comment] 2016-11-26 05:31
So, yes, that's a limitation of the way it's designed. If your TiVo(s) record(s) two copies of the same episode more than a week apart, so will cTiVo.  It does remember episodeIds within the last week to avoid too many dups (and one could easily extend the one-week timeframe), but there does needed to be some sort of time cap, or the Subscription list would expand infinitely.

To be specific, MTSubscription 140-146 checks (an expanded version of) episodeID against prevRecording before confirming a subscription, but every time we save out the subscription list (MTSubscriptionLIst 302-313), we truncate the prevRecording lists to the most recent ones (just ones since oldestPossibleSubscriptionTime MTSubscriptionList 27-48, which is a little complicated to handle multiple TiVos that may not check in regularly, but at least 7 days worth (line 32) and at most 90 (line 35.)

**Comment by ryanchild** [comment] 2016-11-26 06:00
OK thanks for the detailed explanation, I didn't know that was how subscriptions worked. prevRecorded wouldn't expand indefinitely without a time cap, would it? It should cap once it has downloaded every episode of every show matching a subscription?  Which would be maybe 256 bytes * 24 shows * 10 seasons for a typical show?  60KB?  At what point do plist load times become noticeable?

**Comment by mackworth** [comment] 2016-11-26 06:54
Well, let's take NBC Evening News for an example, which has an unlimited number of seasons and 365/year.  cTiVo doesn't know that they're never going to repeat it.

well, I'm happy to let you experiment;  how 'bout I make the 7 days a private configuration option, so you can set it as high as you like?

**Comment by ryanchild** [comment] 2016-11-26 09:09
True.  But without manual intervention the download queue will also grow to be infinitely long in this scenario.. maybe the main difference is the ease of manual intervention?

Sure, a configuration option would be nice.  Maybe just an option to never record dups, regardless of how far apart they are?  Or if you end up using the filesystem somehow like we discussed in #196, that might work too, without needing to worry about plists growing infinitely large from 100s of years of nightly news episodes 😄

**Comment by diverbroski** [comment] 2017-07-18 23:08
Just stumbled on this thread. I'm having the same issue. Tons of duplicates. I had left my queue keep growing... over 2k records, but then I decided to clear it. It would be nice to set it to infinity, so I could choose to never re-download a duplicate.

It would be nice to have some type of "no duplicate" option. Just my 2 cents. Keep up the fantastic work.

**Comment by mackworth** [comment] 2017-07-19 13:46
Just checking that it's behaving as it's supposed to, but these duplicates are repeat recordings separated by more than 30 days?

And would you want it to keep records forever for each show, or just certain ones?

I take it your goal is to record all past episodes of a given show (or else you can just tell TiVo to only record new episodes). Are you keeping those on-line, accessible to the Mac?

**Comment by diverbroski** [comment] 2017-07-19 15:17
Hi Mackworth, I'm not sure how to check, but I think its safe to assume the duplicate recordings are more than 30 days apart.

Use Case Example: Setup TiVo to record all Blue Bloods from all channels. Setup cTiVo to subscribe to Blue Bloods and send converted exports to Drobo where Plex Server is pointed to automatically add new shows to my Plex Media Server.

Net/Net: I'm trying to record every episode from ever season to be available via my Plex Media Server. Plex will automatically make everything look beautiful and hide duplicates, but my old school Mac Pro definitely wastes computing cycles to download, cut commercials, and convert duplicate shows. It would be awesome if cTiVo could maintain a log file for all downloads/conversions to not repeat.

Also, if there are other ways to achieve the use case, please advise. :)

**Comment by mackworth** [comment] 2017-09-07 03:35
So with 3.0 (alpha version at #265), you can now set the option for number of days to save.  It's a hidden option, but if you type "defaults write com.ctivo.ctivo SubscriptionExpirationDays 90", it will keep 90 days worth of information.  You could presumably set this to 1000 and it would save three years worth.  No problem if you're doing episodic shows, but daily shows (news or comedy) might give you some performance problem.  It also should not re-record shows that it can still see, so if the file is still accessible to cTiVo, it should not record a duplicate of it.  I'd love it if you could test these out and let me know.

**Closed** 2017-10-20 02:42 UTC
Labels: enhancement

**Comment by diverbroski** [comment] 2017-11-01 18:08
Hi Mackworth! Sorry for the delayed response, my wife and I just had our first baby and I've been preoccupied. I'm going to configure this today and report back. Also, I was playing around with Hazel (https://www.noodlesoft.com/) to create an automated action to detect duplicates and move them to the trash.

More testing, I will report back!

**Comment by mackworth** [comment] 2017-11-01 18:30
Note in further testing, I also found a case where it was deleting the subscription history, even if it was under 30 days. This is fixed in the current RC2 release.

**Comment by diverbroski** [comment] 2017-11-01 18:34
When I update the default to 1000, do I need to keep my download queue or can I clear it? Right now, I have around 1300 shows in my queue and it is slow to scroll through.

Or is this feature reference the download queue?

**Comment by mackworth** [comment] 2017-11-01 18:37
No, the subscription history is tied to the subscription table (so if you delete the subscription entry, then you’ll lose the history. But nothing to do with the download table.

**Comment by diverbroski** [comment] 2017-11-01 18:42
Fantastic! Different subject, but how do you get a cTiVo to name the resulting file with S01E05? My shows typically come out as TV Show Name – Episode Name. Also, is there a video format that doesn’t convert or is converting required?

If these topics have already been covered, please point me in the right direction. ☺

**Comment by mackworth** [comment] 2017-11-01 18:57
Yup, see the wiki in Advanced Topocs/Filename Templates, and then the one on Video Formats

Happy to answer questions though...
