### ISSUE TITLE
ccExtractor Options

### ISSUE THREAD

**Issue by scottiep** [dscottbuch/cTiVo#102] opened 2015-04-21 13:59 UTC
Has anyone had any experience customizing ccExtractor for cTiVo? I've been unhappy with the subtitle file that is being generated with the default settings--lots of missing characters or inaccuracies. I've gone back to my TiVo to check the CC that gets displayed on my TV and it looks as it should.

I'm not a coder by nature, but if there is something I can put in the "ccExtractor Options" field to improve the subtitle file, I'd like to.

thanks.

**Comment by mackworth** [comment] 2015-04-21 15:13
I've seen the same issue, although the difference may be that TiVo is using the digital stream and ccextractor uses the analog one (see note below).  

If you want to experiment with different options, you don't have to go through the whole download process. Instead you can just invoke the program from Terminal. 

To simulate exactly what cTiVo does, type:
`cd ~/Movies/TivoShows/`
`/Applications/cTiVo.app/Contents/Resources/ccextractor yourOptionsHere -bi -utf8 -s - -o FileName.srt  < FileName.mp2`
where
`yourOptionsHere` is whatever you'd put in the Format Editor's ccExtractor Options
`-bi` forces buffering on input
`-utf8` is the format output (the default was Latin-1 ascii)
`-s` expect a stream ( as we send the file via stdin)
`-`  means get the file from stdin
`-o outfile.srt` means send the output to a file named outfile.srt
`< infile.mp2` tells the OS to send infile.mp2 via stdin

you can get the list of options from running ccextractor all by itself. Above assumes you've got your test file in ~/Movies/TivoShows/  (the cTiVo default).

Note that we have version 0.69, and they've done a lot of work in the last year. I haven't kept up as most of the changes are apparently in unrelated fields. This summer it looks like they're going to finish the CEA708 support (digital captions vs the analog embedded in the stream) which should make a huge improvement in the quality of the output as I believe TiVo provides the digital. 

If you want to compare 0.76, a mac executable version is available here:  https://dl.dropboxusercontent.com/u/21507587/ccextractor If you find any improvement, happy to roll to the new version.

Be sure to use an unconverted MP2 file as input. (Download one using the Decrypt only format). The conversion process damages the analog caption stream.

**Comment by scottiep** [comment] 2015-04-21 18:52
Thanks--I'll definitely try both the newer version as well as running the command in the terminal.

But are you saying that I could be messing up the extractor because I'm using download and convert presets rather than simply downloading a decrypted TiVo file? When I was troubleshooting before starting this thread, I did try a decrypted file but I was unable to find any cc/subtitle file embedded in the MPEG-2, but that was simply using QuickTime Pro and MPEG Streamclip.

**Comment by mackworth** [comment] 2015-04-21 20:22
No, during download/conversion we run the original Mpeg2 data through ccextractor (in parallel with the conversion process). My suggestion was that you use the Decrypt download to get an Mpeg2 file that you can then run through ccextractor multiple times with different options

**Comment by dwhe** [comment] 2015-04-21 20:36
I have been having issues with this exact thing for just over a year now.  I want to add that the problem does not exist just with cTivo but with KMTTG as well, so clearly its not a cTivo issue. I suspect it is either ccextractor or something is going on with the tivo transfer that corrupts the cc. One way of confirming it would be to somehow view the captions on the .TIVO output. If the captions there are bad, then the issue is occurring during the Tivo transfer and before ccextractor even touches it. 

I have done a lot of experimentation and I have noticed some things:  

1) the problem is worse on some channels, but less so on others.   On tivo-downloaded programming from some channels the .srt output is so bad that the captions are illegible. Others have missing words or two to three letters will be misplaced in a line of dialogue (this is the most common issue).  

2)   My cable TV provider (Verizon FIOS) typically has two different channels of the same channel, one is a non-HD channel and one HD channel (for example, TNT  vs TNTHD). Oftentimes I will record the same show on both the non-HD and HD channels to compare the cc output on the .SRT file.  Many times the cc generated from the non-HD show will be much better, if not perfect, compared to the HD one, which often is badly corrupted and illegible (although the cc timing is usually correct). 

Hope this is helpful.

**Comment by mackworth** [comment] 2015-04-21 20:55
I think the issue is the [CEA-708](http://en.wikipedia.org/wiki/CEA-708) vs [EIA-608](http://en.wikipedia.org/wiki/EIA-608) captions, aka digital v analog (technically 608 is still digital, but embedded in the analog tv signal on line 21), and your last point also points to that. ccextractor only pulls out the 608 captions, and most digital devices will rely on the 708 stream. My guess is that the stations with bad captions are converting/compressing/whatever-manipulating the digital stream and that's damaging the signal on line 21. They don't care because the TVs capable of receiving the HD signal are likely using the 708, but ccextractor isn't getting the right data. 

An interesting test would be to attach an analog TV to a TiVo, play the HD-channel version and see if the good or the bad captions come through. If the bad, that would confirm my hypothesis. Not necessarily the other way around, as TiVo may regen the captions on line 21 when it generates the analog signal.

Fortunately, it looks like the ccextractor folks are finally going to try to finish up their 708 code this summer (I tried their current release's "debug-level" 708 support on one TiVo show, and it immediately segfaulted.)

**Comment by scottiep** [comment] 2015-04-21 21:02
thanks dwhe--that's an interesting discovery by you. My cable company does the same--I have both HD and SD versions of most of my channels. I will do a test for myself and see if I get similar results.

**Comment by scottiep** [comment] 2015-04-22 16:43
I'm not skilled as a developer and don't really know about compiling, coding, etc. Can you give me some guidance on how to run the 0.76 script on my decrypted file?

If I simply launch the "build.command" file I get this:

Last login: Wed Apr 22 11:21:41 on ttys001
********:~ *********$ /Users/********/Downloads/ccextractor.0.76/mac/build.command ; exit;
find: ../src/: No such file or directory
find: ../src/: No such file or directory
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
logout

[Process completed]

**Comment by mackworth** [comment] 2015-04-22 18:53
So the build.command file is to compile the source code. Assuming you just want to run the program, just get it from the link I did above: https://dl.dropboxusercontent.com/u/21507587/ccextractor Then you can run that version from your download directory `~/Downloads/ccextractor`

  (If you do actually want to compile it, just go into terminal and type:
    
    ~/Downloads/ccextractor.0.76/mac/
    build.command

**Comment by rjtrudel** [comment] 2015-05-03 06:48
@mackworth.....Hi...I am trying to extract from an .mpg file the closed captioning from a telemundo show that contains both spanish and english captions.  If I use ccextractor on a windows machine it will correctly rip and create 2 .srt files....one in spanish and one in english.  Using ctivo,  in the options I put -12 ( I have also tried -1 and -2 separately), which should rip captions and create 2 .srt files.  No matter what I do, ctivo will only create one .srt file.  Any idea why this would be occurring?

**Comment by mackworth** [comment] 2015-05-03 18:41
Well, basically because cTiVo assumes there's only one track. Can you give me the name of a show that usually contains both languages to play with?  If you also want to experiment, you can try turning on "Don't delete tmp files" and see if -12 creates both files. If so, what are they named, so I can at least avoid deleting them? Be sure to turn off the option after the test, as it will quickly chew up your drive space.

**Comment by mackworth** [comment] 2015-05-13 23:54
Hi, @rjtrudel Any suggestions on a show that creates both tracks?

**Comment by mackworth** [comment] 2015-05-22 22:35
@rjtrudel Hello again. I've tried recording a couple of telenovellas, and haven't found one that has two tracks. I'll close this for now, but if you can give me a sample, I'd love to see if I can make it work.

**Closed by mackworth** 2015-05-22 22:35 UTC
