### ISSUE TITLE
Downloads continually failing

### ISSUE THREAD

**Issue by virtzilla** [dscottbuch/cTiVo#180] opened 2016-08-04 16:59 UTC
I'm seeing an issue with downloads continually failing. I see the same thing with both 2.4.4 and 2.5.0. Downloads appear to complete, then fail and retry.

I see the following in the logs. Note, running OS X 10.10. 

8/4/16 09:49:48.973 secd[311]:  securityd_xpc_dictionary_handler cTiVo[71022] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
8/4/16 09:49:48.974 cTiVo[71022]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

**Comment by mackworth** [comment] 2016-08-04 17:28
Sorry to hear that.  That message is normal. Look in the ctivo logs themselves (from cTivo: Help>Show Logs in Finder, double-click most recent one)

**Comment by virtzilla** [comment] 2016-08-05 04:08
From that log:

2016-08-04 20:55:09:275 MTAppDelegate>applicationDidFinishLaunching:@166>Starting cTiVo; version: 602
2016-08-04 20:55:09:965 MTTiVoManager>netServiceDidResolveAddress:@1796>Got new TiVo: Lounge Bolt at 192.168.1.21
2016-08-04 20:55:09:997 MTTiVo>updateShowsStartingAt:withCount:@375>Initial loading from TiVo Lounge Bolt at URL https://tivo.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-08-04 20:55:10:234 MTDownload>download@1754>Starting URL http://tivo.local.:80/download/The%20Simpsons.TiVo?Container=%2FNowPlaying&id=34 for show The Simpsons: Home Away From Homer in 0.0 seconds
2016-08-04 21:00:35:696 MTDownload>encodeTask@1200> The Simpsons: Home Away From Homer (Lounge Bolt) File /Users/bart/Movies/TiVoShows/The Simpsons- Home Away From Homer.mpg not found after encoding complete
2016-08-04 21:00:36:404 MTTiVoManager>notifyWithTitle:subTitle:isSticky:forNotification:@1430>Notify: TiVo show failed; retrying.../The Simpsons: Home Away From Homer: Can't Download
2016-08-04 21:00:36:406 MTTask>failedTaskCompletion@180>Task encode failed
2016-08-04 21:00:39:995 MTDownload>download@1754>Starting URL http://tivo.local.:80/download/The%20Simpsons.TiVo?Container=%2FNowPlaying&id=34 for show The Simpsons: Home Away From Homer in 3.7 seconds

Have tried several different encoding options, all seem to land me in the same place.

**Comment by mackworth** [comment] 2016-08-05 04:57
Interesting. So, after the encode process, if it's successful, we check for the resulting file, and apparently it's not there.  The file name looks fine. Which Format are you using? if a custom one, try one of the built in ones.  Also, if you can set the Debug level to Detail (in Preferences), you'll get a lot more information about the process.

**Comment by virtzilla** [comment] 2016-08-06 20:37
I tried with the default MPEG-2 encodings to start with, and I know a couple of the other encodings failed (leading me to believe all were), but I don't recall off the top of my head my choices at the time ( I got frustrated after waiting 5 minutes for each xfer only to result in needing another try ;-) )  

I have gotten it to work with the "Decrypted TiVo", though on my initial attempts it was truncating what should have been a 30 minute show to between 15 and 25 seconds. Seems to be working fine now though and I can't replicate my initial attempts (and I blew away the logs and prefs bouncing between 2.4 and 2.5 in experimenting with the above issue). I will turn on the debug log for my next attempts and see if I can find some time to experiment further (and perhaps create a much smaller recording to do so).

**Comment by mackworth** [comment] 2016-08-06 21:05
Yup, I have a 1 minute manually recorded show that I use for testing.  Sorry you can't reproduce, but glad it's working for you, for now at least! Let me know if it starts failing again.  Any chance your cable provider is moving to H.264?  If so, try the 2.5alpha 10 and in Preferences>Channels run the PS Test to see if some channels have migrated.

**Closed by mackworth** 2016-08-06 21:05 UTC
