### ISSUE TITLE
Download keeps failing

### ISSUE THREAD

**Issue by mrfusiontm** [dscottbuch/cTiVo#178] opened 2016-07-07 01:16 UTC
I've got a file that has failed at least 5 or 6 times, I believe its in the encoding phase.
Here's a log file that is fresh as of a couple hours ago that should hopefully show the problem.

Please let me know if you need any other information.

[com.cTiVo.cTiVo 2016-07-06 23-16.log.zip](https://github.com/dscottbuch/cTiVo/files/351202/com.cTiVo.cTiVo.2016-07-06.23-16.log.zip)

**Comment by mrfusiontm** [comment] 2016-07-10 16:05
I'm using cTivo 2.4.4
I was able to view the show in question on my TiVo and download a different show without problems.

**Comment by mackworth** [comment] 2016-07-10 16:33
(Sorry for delay; I thought I answered this already.)

So I see 5 different downloads of the show here.
1) Failed at 23% download due to "network connection was lost" error
2) User rescheduled at 24% complete
3) Failed at 17% download due to "network connection was lost" error
4) this is an interesting one. It's reporting that mencoder is launched, is converting at about 1% per 2 minute check, then jumps from 7% to 100% and is stuck there (so after waiting a while, ctivo cancels the encoding and reschedules it. 
5) it shows reaching 42% of the download, but then the log ends.

Note also
2016-07-06 16:19:19:177 MTTiVo>tivoNetworkCallback@172>Tivo Living Room is now online
2016-07-06 16:34:07:582 MTTiVo>tivoNetworkCallback@172>Tivo Living Room is now online

These (and the "network connection" errors) are indications that there may be some network problem. Maybe wireless dropouts, or the tivo needs to be rebooted, or something wrong with that network connection.

But then one time the file does actually download, and then mencoder has a problem with it.  Try using Handbrake and see if it can convert the file properly.

**Comment by mrfusiontm** [comment] 2016-07-13 12:31
I rebooted the TiVo, the network, my machine and turned off remove tmp files as a test.  The .mpeg file pulled over seems fine, but it still fails on the encoding.  I could not get hand break to encode it either.  It just sat there not doing anything.  The next episode of Preacher is also having this same problem.  I downloaded one other 1/2 hour show from a different channel that encoded just fine.  I'll have to try another hour long show from AMC and see if that has the same problem.

**Comment by mackworth** [comment] 2016-07-13 16:58
Sorry to hear it. Does the encoder log show anything?

**Comment by mrfusiontm** [comment] 2016-07-19 11:43
Well, I rebooted everything and tried it again.  The original file will
download, but still won't encode. The two episodes after that have both
come through fine.
Let's just put this aside for now and call it a fluke unless I  can find
more files that have this problem.

Thanks for the help.

Tom

**Comment by heyneenz** [comment] 2016-08-01 15:54
I am having some similar issues. I did a clean install of ElCap last week and ever since, cTivo hasn't worked the same. I am not sure if it's the machine or something else. It was working great before but now fails to encode. It will go through the download, com skip, encode and then fail at the finish line. 

I've uninstalled and reinstalled cTivo, rebooted the machine and the TiVo itself. I've tried different encoding formats. I'm not sure what to do short of doing another clean install of the OS and starting from scratch. 

[com.cTiVo.cTiVo 2016-07-31 14-56.log.zip](https://github.com/dscottbuch/cTiVo/files/394221/com.cTiVo.cTiVo.2016-07-31.14-56.log.zip)

**Comment by mackworth** [comment] 2016-08-01 23:48
In the log, it says you're using "Handbrake AppleTV.mp4", so apparently not the built-in "Handbrake AppleTV". It looks like this custom format is enabling a simultaneous download/encode, which Handbrake cannot do. Try using the built-in one and see what happens.

**Comment by heyneenz** [comment] 2016-08-02 14:59
Thanks for the response. I used the same thing prior to the clean install. It's really just the built in Handbrake Apple TV setting with the .mp4 wrapper instead of m4v. It worked fine previously. But the regular Apple TV and A duplicate of Handbrake Apple TV with com skip enabled had also previously failed before a deleted and reinstalled cTivo. I should have saved those logs instead of trashing everything. I will try again though and see how it works. Thanks!

**Comment by mackworth** [comment] 2016-08-09 04:58
Ok, let me know if it's still giving you a problem!

**Closed by mackworth** 2016-08-09 04:58 UTC
