### ISSUE TITLE
failing on encode with older Handbrake presets

### ISSUE THREAD

**Issue by scottiep** [dscottbuch/cTiVo#220] opened 2016-12-21 02:32 UTC
I've been using cTiVo for a few years now and first I should applaud everyone who worked on this project because it is fantastic.

And for most of the last year or two, I've used my own presets--they are handbrake presets with some minor adjustments in the "formats" panel. And suddenly, my recordings are failing when encoding. They appear to download fine, but when it then goes to the encode stage, they just fail.

With these same recordings, I've used the "Decrypted TiVo Show" format and that works just as it should.

Nothing has changed on my Mac. I will say that my TiVo account has changed in that I've added another TiVo to the account. But this fail is happening on both TiVo boxes, and it had been working on the first TiVo for some time.

Short of destroying my presets, I'm not sure what to try.

Does anyone have any thoughts?

**Comment by mackworth** [comment] 2016-12-21 02:44
Thanks for the nice compliment!

So, I assume you're using the just released 2.5.0. It has a newer version of Handbrake, in fact several years newer than the one in 2.4.4. The HB presets have been totally revamped in the new version. There's [a list of the ones I built into 2.5.0 halfway down the page here.](https://github.com/dscottbuch/cTiVo/wiki/Video-Formats)  In addition, you can now modify them in the HB GUI and create your own custom presets, which cTiVo will then be able to use.  

On the other hand, the old presets are supposed to still work, but there may be issues there.  Simplest thing would be to select a new HB Format and see if it works for you.

If you're not using 2.5.0, or if you want to try and further diagnose the issue, start by Exporting your custom formats and posting them as text here, so I can see what the situation is.  You should also look in the log file (Help>Show log files) after a failure to see what HB says the problem is.

**Comment by scottiep** [comment] 2016-12-21 03:00
thanks macworth.

As soon as I posted I started poking around in the app contents and I realized that it updated recently--I can see that all the encoders have recent modified dates. So, yes I am using 2.5

I hadn't even noticed that you can use the HB custom presets from the HB GUI. I will try that and see if that works.

Here's one of the ones that is failing:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>captionOptions</key>
		<string></string>
		<key>comSkip</key>
		<false/>
		<key>comSkipOptions</key>
		<string></string>
		<key>edlFlag</key>
		<string></string>
		<key>encoderAudioOptions</key>
		<string>-a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,none -R Auto,Auto -D 0.0,0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 </string>
		<key>encoderOtherOptions</key>
		<string>-f mp4 -4 -X 1280 -Y 720 --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 3.1</string>
		<key>encoderUsed</key>
		<string>HandBrakeCLI</string>
		<key>encoderVideoOptions</key>
		<string>-e x264 -q 20.0 -r 30 --pfr</string>
		<key>filenameExtension</key>
		<string>.m4v</string>
		<key>formatDescription</key>
		<string>HandBrake using the built-in AppleTV 2 preset</string>
		<key>iTunes</key>
		<true/>
		<key>inputFileFlag</key>
		<string>-i</string>
		<key>isFactoryFormat</key>
		<false/>
		<key>isHidden</key>
		<false/>
		<key>mustDownloadFirst</key>
		<true/>
		<key>name</key>
		<string>HandBrake AppleTV 2-30fps progressive</string>
		<key>outputFileFlag</key>
		<string>-o</string>
		<key>regExProgress</key>
		<string> ([\d\.]*?) \%</string>
	</dict>
</array>
</plist>

**Comment by mackworth** [comment] 2016-12-21 03:17
Ok, so loading that into mine, the log shows HB saying says "unknown option -4", presumable about the "-f mp4 -4 -X 1280 -Y 720...".  I don't know what -4 was supposed to do, but when I take it out, the encoding then seems seems to work fine.

**Comment by scottiep** [comment] 2016-12-21 03:43
When I peruse the HB CLI documentation, I cannot find what "-4" does either. But I have 5 custom HB presets in cTiVo and all have "-4" in them. And, I obviously put there. Perhaps it was a HB change or maybe it was benign until now.

I've taken it out of one of my presets and it appears to be working now. It hasn't finished the encode yet, but it looks like that did the trick. Thanks!

**Comment by mackworth** [comment] 2016-12-21 03:54
Great. Let me know how the custom HB stuff works out for you as well.

**Comment by scottiep** [comment] 2016-12-22 22:40
the other odd that that has been happening is that every download and encode I've done in the past several days hasn't had the chapter markers put in for the commercial detection.

Any idea why this has stopped working?

**Comment by mackworth** [comment] 2016-12-22 23:13
Nope.  Are you getting warnings of commercial failure (See notification center in upper right corner)?  How do you know it doesn't have the chapter markers? (Not being rude, maybe they're there, but the app is not showing them.)  There's a [open source project Subler](https://subler.org/), that lets you see exactly what tracks are in the file and even edit them.

And if I can see the logs (say at Detail level) that'll help diagnose.

**Comment by scottiep** [comment] 2016-12-23 01:11
yes, I have been getting the notification that the commercial detection has failed. And, in addition to the notifications, I've noticed that the videos don't have the chapter selection option in iTunes like most of my previous downloads/encodes.

Here's the recent log:

2016-12-22 17:32:06:795 MTDownload>launchDownload@1604>Starting 9 download for Auburn Football Everyday (Bolt 1TB); Format: HandBrake AppleTV 2-ESPN live games;  Mark commercials; Add to iTunes; Generate Subtitles; Keep after iTunes; tivodecode-ng; Program Stream
2016-12-22 17:32:06:920 MTDownload>launchDownload@1790>Starting URL http://dvr-750b.local.:80/download/Auburn%20Football%20Everyday.TiVo?Container=%2FNowPlaying&id=867 for show Auburn Football Everyday in 0.0 seconds
2016-12-22 17:34:16:897 MTTask>failedTaskCompletion@210>Task commercial failed
2016-12-22 17:34:16:897 MTTask>saveLogFileType:fromPath:@177>logFile for task commercial: dyld: Symbol not found: _kCVImageBufferColorPrimaries_ITU_R_2020
  Referenced from: /Applications/cTiVo.app/Contents/MacOS/../lib/libavcodec.57.dylib (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
 in /Applications/cTiVo.app/Contents/MacOS/../lib/libavcodec.57.dylib
2016-12-22 17:34:16:897 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1423>Notify: Detecting Commercials Failed/nNot processing commercials: Commercial Detection Failed
2016-12-22 18:04:19:433 MTiTunes>importIntoiTunes:withArt:@122>Added iTunes track:  Auburn Football Everyday
2016-12-22 18:04:23:153 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1423>Notify: TiVo show transferred./n(null): End Download

**Comment by mackworth** [comment] 2016-12-23 01:19
Oh, oh. Which macOS are you on?

**Comment by scottiep** [comment] 2016-12-23 01:20
10.10.5, Yosemite--it's an older iMac.

**Comment by mackworth** [comment] 2016-12-23 01:24
Can you try the 10.7 version to see what happens?  It looks like the comskip SW got compiled for 10.11 and up.

**Comment by scottiep** [comment] 2016-12-23 02:23
yep--that worked.

**Comment by mackworth** [comment] 2016-12-23 02:28
Great. Hang on for a day or two while I regenerate the binaries. I'd love to have you try it before I update the main distribution.

**Comment by scottiep** [comment] 2016-12-23 02:35
Will do--glad to help if I can.

**Comment by mackworth** [comment] 2016-12-26 22:28
@scottiep can you try this one out?

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by scottiep** [comment] 2016-12-27 00:29
it crashes on launch:

Process:               cTiVo [11349]
Path:                  /Applications/cTiVo.app/Contents/MacOS/cTiVo
Identifier:            com.cTiVo.cTiVo
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           cTiVo [11349]
User ID:               501

Date/Time:             2016-12-26 18:28:08.889 -0600
OS Version:            Mac OS X 10.10.5 (14F2109)
Report Version:        11
Anonymous UUID:        0775DE5E-D5AC-B43C-87FE-01DE1C422BC0


Time Awake Since Boot: 80000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/samba3/libsmbclient.dylib
  Referenced from: /Applications/cTiVo.app/Contents/MacOS/cTiVo
  Reason: image not found

Binary Images:
    0x7fff688e9000 -     0x7fff6891f92f  dyld (353.2.4) <708E385E-50C6-32A3-983C-42E97BEE4346> /usr/lib/dyld

Model: iMac11,3, BootROM IM112.0057.B03, 4 processors, Intel Core i7, 2.93 GHz, 12 GB, SMC 1.59f2
Graphics: ATI Radeon HD 5750, ATI Radeon HD 5750, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x02FE, 0x45424A3231554538424655302D444A2D4620
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x02FE, 0x45424A3231554538424655302D444A2D4620
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1333 MHz, 0x8634, 0x535550455254414C454E5430320000000000
Memory Module: BANK 1/DIMM1, 4 GB, DDR3, 1333 MHz, 0x8634, 0x535550455254414C454E5430320000000000
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 4.0.74.0-P2P
Bluetooth: Version 4.3.6f4 17916, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: WDC WD1001FALS-40Y6A0, 1 TB
Serial ATA Device: HL-DT-STDVDRW  GA32N
USB Device: Hub
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Internal Memory Card Reader
USB Device: Hub
USB Device: Built-in iSight
USB Device: IR Receiver
FireWire Device: Rev2, Drobo, Up to 800 Mb/sec
Thunderbolt Bus:

**Comment by mackworth** [comment] 2016-12-27 00:31
Thanks. I'll fix

**Comment by mackworth** [comment] 2016-12-27 05:01
Hi, please try again. Silly mistake on my part;  same URL, but should be v712 now
https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by scottiep** [comment] 2016-12-27 20:05
OK--it launches and works now, but the commercial detection and chapter markers still aren't working.

**Comment by mackworth** [comment] 2016-12-27 20:50
Huh. Can you send me a portion of the log?

**Comment by scottiep** [comment] 2016-12-27 21:07
yep--it'll be a few hours though. I'm at work and that iMac that I use cTiVo on is on my home network with my TiVos.

**Comment by scottiep** [comment] 2016-12-28 00:19
here's the log:

2016-12-27 07:33:16:168 MTAppDelegate>cleanup@1059>cTiVo exiting
2016-12-27 07:37:54:337 MTAppDelegate>applicationDidFinishLaunching:@205>Starting cTiVo; version: 712
2016-12-27 07:37:55:803 MTTiVoManager>netServiceDidResolveAddress:@1689>Got new TiVo: GR at 10.0.1.30
2016-12-27 07:37:55:907 MTTiVoManager>netServiceDidResolveAddress:@1689>Got new TiVo: Bolt 1TB at 10.0.1.20
2016-12-27 07:37:56:012 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo GR at URL https://DVR-D238.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-12-27 07:37:56:014 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Bolt 1TB at URL https://DVR-750B.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-12-27 07:39:43:579 MTAppDelegate>cleanup@1059>cTiVo exiting
2016-12-27 07:39:47:601 MTAppDelegate>applicationDidFinishLaunching:@205>Starting cTiVo; version: 712
2016-12-27 07:39:48:855 MTTiVoManager>netServiceDidResolveAddress:@1689>Got new TiVo: Bolt 1TB at 10.0.1.20
2016-12-27 07:39:49:003 MTTiVoManager>netServiceDidResolveAddress:@1689>Got new TiVo: GR at 10.0.1.30
2016-12-27 07:39:49:137 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Bolt 1TB at URL https://DVR-750B.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-12-27 07:39:49:138 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo GR at URL https://DVR-D238.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-12-27 07:39:57:309 MTDownload>launchDownload@1606>Starting 9 download for Auburn Football Everyday (Bolt 1TB); Format: HandBrake AppleTV 2-30fps progressive;  Mark commercials; Add to iTunes; Generate Subtitles; Keep after iTunes; tivodecode-ng; Program Stream
2016-12-27 07:39:57:605 MTDownload>launchDownload@1792>Starting URL http://dvr-*******
Container=%2FNowPlaying&id=1145 for show Auburn Football Everyday in 0.0 seconds
2016-12-27 07:42:27:896 MTTask>failedTaskCompletion@210>Task commercial failed
2016-12-27 07:42:27:974 MTTask>saveLogFileType:fromPath:@177>logFile for task commercial: dyld: Library not loaded: @executable_path/../lib/libiconv.2.dylib
  Referenced from: /Applications/cTiVo.app/Contents/lib/libavutil.55.dylib
  Reason: Incompatible library version: libavutil.55.dylib requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0
2016-12-27 07:42:27:974 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1423>Notify: Detecting Commercials Failed/nNot processing commercials: Commercial Detection Failed
2016-12-27 08:05:30:629 MTiTunes>importIntoiTunes:withArt:@122>Added iTunes track:  Auburn Football Everyday
2016-12-27 08:05:32:615 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1423>Notify: TiVo show transferred./n: End Download

**Comment by mackworth** [comment] 2016-12-28 03:25
That's odd. It says it's not finding the file `libiconv.2.dylib` (so it sees an older version in the system), but it's in the file I sent you, and it's properly pointed to by comskip and it's the newer version.... 
You're running the file I sent you, as it says 712. 

Question 1) Just checking: it looks like you moved it into your Applications folder as cTiVo, correct?  (Not required nor a problem, but I'm just making sure it's not accidentally calling into a different version of ctivo)
Question 2) can you try running Default as the Format? It will probably fail immediately after download as well.
Question 3) Using the HB Default, can you turn off commercial skipping/marking but leave on subtitles, and let me know if the subtitles work?

Thank you helping me figure this out.  It's difficult when I don't have an older system to work with.

**Comment by scottiep** [comment] 2016-12-28 04:09
I did move the beta into the Applications folder--however I didn't trash the old one (2.5). I just moved that one to the desktop. I wonder if not trashing it is causing issues.

I did just run the beta on the same TV program using the HB default. I turned off the commercial mark and left subtitles on. It downloaded and encoded, but upon completion the mp4 that it created will not open in any QuickTime program. It did open in VLC and it does have a subtitle track. But QT definitely doesn't like it.

**Comment by mackworth** [comment] 2016-12-30 04:28
ok, and trying again...

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by mackworth** [comment] 2016-12-31 21:41
any luck with that one?  I'm pretty sure it'll work this time.

**Comment by scottiep** [comment] 2016-12-31 21:44
on HB default, it still creates an mp4 that QT and the OS won't open. When I use one of my custom presets it encodes fine, but still doesn't detect commercials.

**Comment by mackworth** [comment] 2016-12-31 21:45
I'll worry about the first part later, but can you paste log for  the second part?

**Comment by scottiep** [comment] 2016-12-31 22:52
2016-12-31 15:10:12:425 MTDownload>launchDownload@1606>Starting 9 download for Auburn Football Everyday (Bolt 1TB); Format: HandBrake AppleTV 2-30fps progressive;  Mark commercials; Add to iTunes; Generate Subtitles; Keep after iTunes; tivodecode-ng; Program Stream
2016-12-31 15:10:12:691 MTDownload>launchDownload@1795>Starting URL http://dvr-******* for show Auburn Football Everyday in 0.0 seconds
2016-12-31 15:13:27:246 MTTask>failedTaskCompletion@214>Task commercial failed
2016-12-31 15:13:27:247 MTTask>saveLogFileType:fromPath:@181>logFile for task commercial: dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/cTiVo.app/Contents/MacOS/../lib/libgnutls.30.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/cTiVo.app/Contents/MacOS/../lib/libgnutls.30.dylib
  Expected in: /usr/lib/libSystem.B.dylib

2016-12-31 15:13:27:247 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1423>Notify: Detecting Commercials Failed/nNot processing commercials: Commercial Detection Failed
2016-12-31 15:39:45:632 MTiTunes>importIntoiTunes:withArt:@122>Added iTunes track:  Auburn Football Everyday
2016-12-31 15:39:45:835 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1423>Notify: TiVo show transferred./n: End Download
2016-12-31 16:05:52:703 MTAppDelegate>cleanup@1059>cTiVo exiting
2016-12-31 16:38:36:787 MTAppDelegate>applicationDidFinishLaunching:@205>Starting cTiVo; version: 714
2016-12-31 16:38:52:449 MTTiVoManager>netServiceDidResolveAddress:@1689>Got new TiVo: GR at 10.0.1.30
2016-12-31 16:38:52:531 MTTiVoManager>netServiceDidResolveAddress:@1689>Got new TiVo: Bolt 1TB at 10.0.1.20
2016-12-31 16:38:52:612 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo GR at URL https://DVR-*******
2016-12-31 16:38:52:614 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Bolt 1TB at URL https://DVR-*******

**Comment by mackworth** [comment] 2017-01-06 03:53
Ok, think I've got it now. Please try again:

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by mackworth** [comment] 2017-01-06 23:25
Should be fixed by [2.5.1beta3 release](https://github.com/dscottbuch/cTiVo/releases). Let me know if there's still a problem!

**Closed by mackworth** 2017-01-06 23:25 UTC

**Comment by scottiep** [comment] 2017-01-07 02:29
Eureka! That did it--thanks!
